### ISSUE TITLE
Links retornam 404 - Teste Piloto - Wiki

### ISSUE THREAD

**Issue by ErickGiffoni** [Interacao-Humano-Computador/2020.1-AliExpress#54]
Pessoal, os links para os relatórios (pdf e docx) do Teste Piloto, na wiki, estão retornando 404.

ABS.

Edit: parece que isso já havia sido relatado em #51

**Comment by ErickGiffoni** [comment]
Para ser mais específico, os links que me refiro estão aqui -> https://interacao-humano-computador.github.io/2020.1-AliExpress/#/./pages/design_avaliation_development/pilotTestAvaliation/pilotTestAvaliation?id=execução-do-teste-piloto

**Comment by DanilloGS** [comment]
Issue foi resolvida
